apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-deployment

spec:
  replicas: 4
  template:
    metadata:
      labels:
        component: training-app
    spec:
      containers:
        - name: training-app-container
          image: manojkumar9953873435/dockerkube:latest
          ports:
          - containerPort: 80
          env:
            - name: REDIS_HOST
              value: redis-service
            - name: REDIS_PORT
              value: '6379'
            - name: POSTGRES_HOST
              value: postgres-service
            - name: POSTGRES_USER
              value: hello_flask
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_DB
              value: docker_kube_db
            - name: DATABASEPASSWORD
              valueFrom:
                secretKeyRef:
                  name: databasepassword
                  key: DATABASEPASSWORD

  selector:
    matchLabels:
      component: training-app